// Generated by CoffeeScript 1.6.1
var PlaceRobot, RobotLand, isEdge, robot;

robot = {
  input1: 1,
  input2: 4,
  input3: "n"
};

RobotLand = function(input1, input2, input3) {
  var RobotLanded, landX, landY, oriented;
  landX = input1;
  landY = input2;
  oriented = input3;
  RobotLanded = [landX, landY, oriented];
  return PlaceRobot(RobotLanded);
};

PlaceRobot = function(landingData) {
  return console.log(landingData);
};

RobotLand(robot);

isEdge = function(x, y, ylimit, xlimit) {
  var E, N, S, W;
  if (x === 0) {
    S = "edge";
    console.log(S);
  }
  if (y === ylimit) {
    N = "edge";
    console.log(N);
  }
  if (x === 0) {
    W = "edge";
    console.log(W);
  }
  if (x === xlimit) {
    E = "edge";
    console.log(E);
  }
};

isEdge(3, 9, 6, 9);
